### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by aamaanaa** [EvilBytecode/GoCodepulzeKiller#1]
lets say i have a program that downloads another program

- would i get the pid of my own program and patch my self?
- or, would i need to create a suspended progress of some exe that is to be started, patch asmi, and continue?
- or just make a progress and run asmi patch on it?

**Comment by EvilBytecode** [comment]
hi, please star and follow this repo that would be really fine 👍 beacuse that would support me.
pid isnt needed beacuse it waits for new powershell window to be created and when it is, then it will patch the window 
if youre wondering how to get pid you can simply go to powershell window and do ```$pid```` thats all but for the code it isnt needed

**Comment by aamaanaa** [comment]
i see

so lets say a go program opens. it would start a suspended powershell with for example a script to invoke mimkatz, patch it using this script,

and then resume it?

**Comment by EvilBytecode** [comment]
nope the current one just does that it patches powershell windows all you can do is make other script that opens and does some bullsh all you gotta do is use brain 💯

**Comment by EvilBytecode** [comment]
no response, will be closed.
